# -*- encoding : utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


imd_ad = Sector.create(name: "Administração Central"                   , description: "Departamento do Instituto Metrópole Digital")
data_c = Sector.create(name: "IMD Datacenter e Suporte Técnico"        , description: "Departamento do Instituto Metrópole Digital")
mes_pr = Sector.create(name: "Mestrado Profissional"                   , description: "Departamento de mestrado profissional")
dep_ep = Sector.create(name: "Especialização e Residências"            , description: "Departamento de especialização")
tec_ti = Sector.create(name: "Cursos Técnicos"                         , description: "Departamento dos Cursos Técnicos do IMD")
dep_ti = Sector.create(name: "BTI"                                     , description: "Departamento de Bacharelado em Tecnologia da Informação")
dep_es = Sector.create(name: "ES"                                     , description: "Departamento de Bacharelado em Engenharia de Software")
dep_be = Sector.create(name: "BTI e ES"                                , description: "Departamento comum de ES e BTI")
incuba = Sector.create(name: "INOVA"                                   , description: "Departamento das empresas incubadas ou âncoras")
imd_ed = Sector.create(name: "Departamento de Informática Educacional" , description: "Departamento de cursos/aulas de Informática Educacional")
psicol = Sector.create(name: "Psicologia e Serviço Social"             , description: "Departamento de apoio a alunos e servidores")

lab_info       = RoomType.create(name: "Laboratório de Informática" , description: "Laboratório para uso diverso.")
administrativo = RoomType.create(name: "Administrativo"             , description: "Sala atividades técnico administrativas do instituto.")
reuniao        = RoomType.create(name: "Sala de Reuniões"           , description: "Sala de reuniões e video-conferências.")
professores    = RoomType.create(name: "Sala de Professores"        , description: "Sala de docentes da instituição.")
auditorio      = RoomType.create(name: "Auditório"                  , description: "Auditório para eventos.")
sala_de_aula   = RoomType.create(name: "Sala de Aula"               , description: "Sala de aula sem computadores.")
lab_pesquisa   = RoomType.create(name: "Laboratório de Pesquisa"    , description: "Laboratório para pesquisa de grupos da instituição.")
empresa        = RoomType.create(name: "Empresa"                    , description: "Sala para empresa com sede na instituição.")
incubada       = RoomType.create(name: "Incubadação"                , description: "Sala para empresa incubada pela instituição.")

######################### PRIMEIRO PAVIMENTO #########################

tec_place = Place.create(code: "A101" , name: "Laboratório de Informática", capacity: 40, sector_ids: tec_ti.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A102" , name: "Laboratório de Informática"            , capacity: 40, sector_ids: tec_ti.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A103" , name: "Laboratório de Informática"            , capacity: 40, sector_ids: tec_ti.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A104" , name: "Laboratório de Informática"            , capacity: 40, sector_ids: tec_ti.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A105" , name: "Gráfica"                               , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A106" , name: "Sala de Reuniões"                      , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "A107" , name: "Rack"                                  , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A108" , name: "Mini-Estúdio"                          , capacity: 00, sector_ids: imd_ed.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A109" , name: "Equipe de Revisão"                     , capacity: 00, sector_ids: imd_ed.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A110" , name: "Equipe de Diagramção e Vídeo"          , capacity: 00, sector_ids: imd_ed.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A111" , name: "Equipe do Ambiente Virtual"            , capacity: 00, sector_ids: imd_ed.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B101" , name: "Sala de Reuniões"                      , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B102" , name: "Diretoria CIVT"                        , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B103" , name: "Secretaria"                            , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B104" , name: "Direção IMD"                           , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B105" , name: "Secretaria"                            , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B106" , name: "Gerência Administrativa"               , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B107" , name: "Gerência Técnica"                      , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B108" , name: "Setor de Recursos Humanos"             , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B109" , name: "Sala de Reuniões"                      , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B110" , name: "Setor de Compras"                      , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B111" , name: "Sala de Reuniões"                      , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B112" , name: "Setor de Patrimônio"                   , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B113" , name: "Almoxarifado"                          , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B114" , name: "Setor Administrativo"                  , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B115" , name: "Setor Técnico"                         , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B115a", name: "Diretor Técnico"                       , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B115b", name: "Sala de Manutenção"                    , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B115c", name: "Equipamentos de Informática"           , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B116" , name: "Secretaria de Cursos de Graduação"     , capacity: 00, sector_ids: dep_ti.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B117" , name: "Secretaria de Cursos Técnicos"         , capacity: 00, sector_ids: tec_ti.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B118" , name: "Almoxafirado"                          , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B119" , name: "Datacenter"                            , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B120" , name: "Sala de Apoio"                         , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)

######################### SEGUNDO PAVIMENTO #########################

Place.create(code: "A201" , name: "Secretaria"                            , capacity: 00, sector_ids: tec_ti.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A201a", name: "Coordenação"                           , capacity: 00, sector_ids: tec_ti.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A202" , name: "Laborartório de Informática"           , capacity: 20, sector_ids: tec_ti.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A203" , name: "Sala de apoio"                         , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A203a", name: "Sala de Racks"                         , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A203b", name: "Professores Técnico"                   , capacity: 04, sector_ids: tec_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A204" , name: "Laborartório de Informática"           , capacity: 20, sector_ids: tec_ti.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A205" , name: "Laborartório de Informática"           , capacity: 20, sector_ids: tec_ti.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A206" , name: "Sala de Atendimento"                   , capacity: 00, sector_ids: psicol.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A207" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A208" , name: "Pedagogia e Psicologia"                , capacity: 00, sector_ids: psicol.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A209" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A210" , name: "Pedagogia e Assistência Social"        , capacity: 00, sector_ids: psicol.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A211" , name: "Coordenação Pedagógica"                , capacity: 03, sector_ids: psicol.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A212" , name: "Laborartório de Informática"           , capacity: 20, sector_ids: tec_ti.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A213" , name: "Professores Técnico"                   , capacity: 06, sector_ids: tec_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A214" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A215" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A216" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A217" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A218" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A219" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A220" , name: "Professores Técnico"                   , capacity: 06, sector_ids: tec_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A221" , name: "Refeitório"                            , capacity: 00, sector_ids: imd_ad.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A222" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A223" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A224" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A225" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A226" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "A227" , name: "Professores BTI"                       , capacity: 02, sector_ids: dep_ti.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B201" , name: "Sala de Apoio"                         , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: administrativo.id)
Place.create(code: "B201a", name: "Sala de Racks"                         , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B202" , name: "Laboratório de Informática"            , capacity: 00, sector_ids: mes_pr.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "B203" , name: "Sala de Aula"                          , capacity: 64, sector_ids: dep_be.id, reservable: true , room_type_id: sala_de_aula.id)
Place.create(code: "B204" , name: "Sala de Aula"                          , capacity: 64, sector_ids: dep_be.id, reservable: true , room_type_id: sala_de_aula.id)
Place.create(code: "B205" , name: "Auditório"                             , capacity:192, sector_ids: imd_ad.id, reservable: true , room_type_id: auditorio.id)
Place.create(code: "B206" , name: "Auditório"                             , capacity: 60, sector_ids: imd_ad.id, reservable: true , room_type_id: auditorio.id)

######################### TERCEIRO PAVIMENTO #########################

bti_place= Place.create(code: "A301" , name: "Laboratório de Informática" , capacity: 30, sector_ids: dep_be.id, reservable: true, room_type_id: lab_info.id)
Place.create(code: "A302" , name: "Sala de Apoio"                         , capacity: 00, sector_ids: data_c.id, reservable: true, room_type_id: administrativo.id)
Place.create(code: "A302a", name: "Sala de Racks"                         , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "A303" , name: "Laboratório de Informática"            , capacity: 30, sector_ids: dep_be.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A304" , name: "Laboratório de Informática"            , capacity: 35, sector_ids: dep_ep.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A305" , name: "Laboratório de Informática"            , capacity: 40, sector_ids: dep_be.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A306" , name: "Sala de Aula"                          , capacity: 64, sector_ids: dep_be.id, reservable: true , room_type_id: sala_de_aula.id)
Place.create(code: "A307" , name: "Laboratório de Informática"            , capacity: 40, sector_ids: dep_be.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "A308" , name: "Sala de Aula"                          , capacity: 40, sector_ids: dep_be.id, reservable: true , room_type_id: sala_de_aula.id)
Place.create(code: "A309" , name: "Laboratório de Informática"            , capacity: 40, sector_ids: dep_be.id, reservable: true , room_type_id: lab_info.id)
Place.create(code: "B301" , name: "Sala de Apoio"                         , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: administrativo.id)
Place.create(code: "B301a", name: "Sala de Racks"                         , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B302" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B303" , name: "Professores Visitantes"                , capacity: 02, sector_ids: dep_es.id, reservable: true , room_type_id: professores.id)
Place.create(code: "B304" , name: "Professores Visitantes"                , capacity: 02, sector_ids: dep_es.id, reservable: true , room_type_id: professores.id)
Place.create(code: "B305" , name: "Professores ES"                        , capacity: 02, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B306" , name: "Professores ES"                        , capacity: 02, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B307" , name: "Sala de Reuniões"                      , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B307a", name: "Sala de Reuniões"                      , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B308" , name: "Coordenação Mestrado Profissional"     , capacity: 00, sector_ids: mes_pr.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B309" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B310" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B311" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B312" , name: "Professores ES"                        , capacity: 02, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B313" , name: "Professores ES"                        , capacity: 02, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B314" , name: "Coord. da Especialização e Residências", capacity: 00, sector_ids: dep_ep.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B315" , name: "Laboratório de Pesquisa"               , capacity: 00, sector_ids: dep_es.id, reservable: false, room_type_id: lab_pesquisa.id)
Place.create(code: "B316" , name: "Laboratório de Pesquisa"               , capacity: 00, sector_ids: dep_es.id, reservable: false, room_type_id: lab_pesquisa.id)
Place.create(code: "B317" , name: "Laboratório de Pesquisa"               , capacity: 00, sector_ids: dep_es.id, reservable: false, room_type_id: lab_pesquisa.id)
Place.create(code: "B318" , name: "Laboratório de Pesquisa"               , capacity: 00, sector_ids: dep_es.id, reservable: false, room_type_id: lab_pesquisa.id)
Place.create(code: "B319" , name: "Laboratório de Pesquisa"               , capacity: 00, sector_ids: dep_es.id, reservable: false, room_type_id: lab_pesquisa.id)
Place.create(code: "B320" , name: "Laboratório de Pesquisa"               , capacity: 00, sector_ids: dep_es.id, reservable: false, room_type_id: lab_pesquisa.id)
Place.create(code: "B321" , name: "Sala de Reuniões"                      , capacity: 80, sector_ids: imd_ad.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B322" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B323" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B324" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B325" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B326" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)
Place.create(code: "B327" , name: "Professores ES"                        , capacity: 01, sector_ids: dep_es.id, reservable: false, room_type_id: professores.id)

######################### QUARTO PAVIMENTO #########################

bes_place = Place.create(code: "A401" , name: "Sala de Reuniões"          , capacity: 00, sector_ids: incuba.id, reservable: true , room_type_id: reuniao.id)

Place.create(code: "A402" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A403" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A404" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A405" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A406" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A407" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A408" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A409" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A410" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A411" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A412" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A413" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A414" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "A415" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B401" , name: "Sala de Apoio"                         , capacity: 00, sector_ids: imd_ad.id, reservable: true , room_type_id: administrativo.id)
Place.create(code: "B401a", name: "Sala de Racks"                         , capacity: 00, sector_ids: data_c.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B402" , name: "Secretaria"                            , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B402a", name: "Chefia"                                , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: administrativo.id)
Place.create(code: "B403" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B404" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B405" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B406" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B407" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B408" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B409" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B410" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B411" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B412" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B413" , name: "Sala de Reuniões"                      , capacity: 00, sector_ids: incuba.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B414" , name: "Sala de Reuniões"                      , capacity: 00, sector_ids: incuba.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B415" , name: "Sala de Reuniões"                      , capacity: 00, sector_ids: incuba.id, reservable: true , room_type_id: reuniao.id)
Place.create(code: "B416" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B417" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B418" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B419" , name: "Empresa"                               , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: empresa.id)
Place.create(code: "B420" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B421" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B422" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B423" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B425" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B427" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B429" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B431" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B433" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B435" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)
Place.create(code: "B436" , name: "Incubada"                              , capacity: 00, sector_ids: incuba.id, reservable: false, room_type_id: incubada.id)


User.create(role: "admin", email: "admin@example.com", password: "rootadmin", name: "Admin", cpf: "092.092.092-92", sector_ids: 1)
User.create(role: "receptionist", email: "recep@example.com", password: "rootadmin", name: "Recep", cpf: "192.092.092-92", sector_ids: 1)

bes_user = User.create(role: "basic", email: "marcel@example.com", password: "rootadmin", name: "Marcel BES", cpf: "096.092.092-96", sector_ids: dep_es.id)
bti_user = User.create(role: "basic", email: "jose@example.com", password: "rootadmin", name: "José BTI", cpf: "097.092.092-97", sector_ids: dep_ti.id)
tec_user = User.create(role: "basic", email: "mariana@example.com", password: "rootadmin", name: "Mariana Técnico TI", cpf: "087.092.092-97", sector_ids: tec_ti.id)

User.create(role: "sector_admin", email: "sector_admin_dep_ti@example.com", password: "rootadmin", name: "Admin do Setor BTI", cpf: "093.092.092-93", sector_ids: dep_ti.id)
User.create(role: "sector_admin", email: "sector_admin_tec_ti@example.com", password: "rootadmin", name: "Admin do Setor Tec TI", cpf: "093.091.092-93", sector_ids: tec_ti.id)
User.create(role: "sector_admin", email: "sector_admin_dep_es@example.com", password: "rootadmin", name: "Admin do Setor BES", cpf: "093.091.082-93", sector_ids: dep_es.id)

User.create(role: "secretary", email: "secretary_dep_ti@example.com", password: "rootadmin", name: "Secretário BTI", cpf: "11111111111111", sector_ids: dep_ti.id)
User.create(role: "secretary", email: "secretary_tec_ti@example.com", password: "rootadmin", name: "Secretário Tec TI", cpf: "22222222222222", sector_ids: tec_ti.id)
User.create(role: "secretary", email: "secretary_dep_es@example.com", password: "rootadmin", name: "Secretário BES", cpf: "33333333333333", sector_ids: dep_es.id)

Reservation.create(user_id: bes_user.id, reason: "Palestra." , date: Date.today - 1.day, begin_time: Time.now, end_time: Time.now + 1.hour, place_id:bes_place.id, status: "pending", created_by_id: 1)
Reservation.create(user_id: bes_user.id, reason: "Minicurso.", date: Date.today + 2.day, begin_time: Time.now, end_time: Time.now + 2.hour, place_id:tec_place.id, status: "pending", created_by_id: 1)
Reservation.create(user_id: bes_user.id, reason: "Reunião."  , date: Date.today + 3.day, begin_time: Time.now, end_time: Time.now + 3.hour, place_id:bti_place.id, status: "pending", created_by_id: 1)
Reservation.create(user_id: bti_user.id, reason: "Palestra." , date: Date.today - 1.day, begin_time: Time.now, end_time: Time.now + 1.hour, place_id:bes_place.id, status: "pending", created_by_id: 1)
Reservation.create(user_id: bti_user.id, reason: "Minicurso.", date: Date.today + 3.day, begin_time: Time.now, end_time: Time.now + 2.hour, place_id:tec_place.id, status: "pending", created_by_id: 1)
Reservation.create(user_id: bti_user.id, reason: "Reunião."  , date: Date.today + 4.day, begin_time: Time.now, end_time: Time.now + 3.hour, place_id:bti_place.id, status: "pending", created_by_id: 1)
Reservation.create(user_id: tec_user.id, reason: "Palestra." , date: Date.today - 1.day, begin_time: Time.now, end_time: Time.now + 1.hour, place_id:bes_place.id, status: "pending", created_by_id: 1)
Reservation.create(user_id: tec_user.id, reason: "Minicurso.", date: Date.today + 4.day, begin_time: Time.now, end_time: Time.now + 2.hour, place_id:tec_place.id, status: "pending", created_by_id: 1)
Reservation.create(user_id: tec_user.id, reason: "Reunião."  , date: Date.today + 5.day, begin_time: Time.now, end_time: Time.now + 3.hour, place_id:bti_place.id, status: "pending", created_by_id: 1)

projetor = ObjectResource.create(name: "Projetor", description: "Datashow fixo.")
computador= ObjectResource.create(name: "Computador", description: "Computador fixo.")

Vehicle.create(plate: "MYL-6222", car_model: "Doblo", description: "Amplo espaço interno", capacity: 8)
Vehicle.create(plate: "MNL-6423", car_model: "L200", description: "Caminhonete", capacity: 2)
Driver.create(name: "João")


bes_place.object_resources << projetor
tec_place.object_resources << projetor
bti_place.object_resources << projetor

bes_place.object_resources << computador
tec_place.object_resources << computador
bti_place.object_resources << computador
