# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ObjectResourcesController do

  # This should return the minimal set of attributes required to create a valid
  # ObjectResource. As you add validations to ObjectResource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ObjectResourcesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all object_resources as @object_resources" do
      object_resource = ObjectResource.create! valid_attributes
      get :index, {}, valid_session
      assigns(:object_resources).should eq([object_resource])
    end
  end

  describe "GET show" do
    it "assigns the requested object_resource as @object_resource" do
      object_resource = ObjectResource.create! valid_attributes
      get :show, {:id => object_resource.to_param}, valid_session
      assigns(:object_resource).should eq(object_resource)
    end
  end

  describe "GET new" do
    it "assigns a new object_resource as @object_resource" do
      get :new, {}, valid_session
      assigns(:object_resource).should be_a_new(ObjectResource)
    end
  end

  describe "GET edit" do
    it "assigns the requested object_resource as @object_resource" do
      object_resource = ObjectResource.create! valid_attributes
      get :edit, {:id => object_resource.to_param}, valid_session
      assigns(:object_resource).should eq(object_resource)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ObjectResource" do
        expect {
          post :create, {:object_resource => valid_attributes}, valid_session
        }.to change(ObjectResource, :count).by(1)
      end

      it "assigns a newly created object_resource as @object_resource" do
        post :create, {:object_resource => valid_attributes}, valid_session
        assigns(:object_resource).should be_a(ObjectResource)
        assigns(:object_resource).should be_persisted
      end

      it "redirects to the created object_resource" do
        post :create, {:object_resource => valid_attributes}, valid_session
        response.should redirect_to(ObjectResource.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved object_resource as @object_resource" do
        # Trigger the behavior that occurs when invalid params are submitted
        ObjectResource.any_instance.stub(:save).and_return(false)
        post :create, {:object_resource => {  }}, valid_session
        assigns(:object_resource).should be_a_new(ObjectResource)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ObjectResource.any_instance.stub(:save).and_return(false)
        post :create, {:object_resource => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested object_resource" do
        object_resource = ObjectResource.create! valid_attributes
        # Assuming there are no other object_resources in the database, this
        # specifies that the ObjectResource created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ObjectResource.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => object_resource.to_param, :object_resource => { "these" => "params" }}, valid_session
      end

      it "assigns the requested object_resource as @object_resource" do
        object_resource = ObjectResource.create! valid_attributes
        put :update, {:id => object_resource.to_param, :object_resource => valid_attributes}, valid_session
        assigns(:object_resource).should eq(object_resource)
      end

      it "redirects to the object_resource" do
        object_resource = ObjectResource.create! valid_attributes
        put :update, {:id => object_resource.to_param, :object_resource => valid_attributes}, valid_session
        response.should redirect_to(object_resource)
      end
    end

    describe "with invalid params" do
      it "assigns the object_resource as @object_resource" do
        object_resource = ObjectResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ObjectResource.any_instance.stub(:save).and_return(false)
        put :update, {:id => object_resource.to_param, :object_resource => {  }}, valid_session
        assigns(:object_resource).should eq(object_resource)
      end

      it "re-renders the 'edit' template" do
        object_resource = ObjectResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ObjectResource.any_instance.stub(:save).and_return(false)
        put :update, {:id => object_resource.to_param, :object_resource => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested object_resource" do
      object_resource = ObjectResource.create! valid_attributes
      expect {
        delete :destroy, {:id => object_resource.to_param}, valid_session
      }.to change(ObjectResource, :count).by(-1)
    end

    it "redirects to the object_resources list" do
      object_resource = ObjectResource.create! valid_attributes
      delete :destroy, {:id => object_resource.to_param}, valid_session
      response.should redirect_to(object_resources_url)
    end
  end

end
